pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 2.7
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip platformio
    platformio update
  displayName: 'Install prerequisites'

- script: |
    export PLATFORMIO_BUILD_FLAGS='-BUILD_CI=\"TRUE\"''
    platformio run
  condition: succeededOrFailed()
  displayName: 'Build project'